### ISSUE TITLE
[crit] Recode on aarch64

### ISSUE THREAD

**Issue by blackgeorge-boom** [ssrg-vt/TransProc#18]
Hello!

I want to do a migration aarch64->x86-64 for the simple `loop` test.

However, it seems that `crit recode` fails (both on aarch64 and x86-64):

```bash
python3 ~/TransProc/criu-3.15/crit/crit recode . ./x86-64/ x86-64 loop ./bin/ y

('found vma at idx', 11, 11)
('Dumped image file', './x86-64/mm-14775.img')
('Dumped image file', './x86-64/pagemap-14775.img')
('pagemap image file transformed',)
('mm image file transformed',)
('fs_base', '0x801490')
(OrderedDict([('ax', 0), ('dx', 0), ('cx', 0), ('bx', 0), ('si', 0), ('di', 0), ('bp', 0), ('sp', 0), ('r8', 0), ('r9', 0), ('r10', 0), ('r11', 0), ('r12', 0), ('r13', 0), ('r14', 0), ('r15', 0), ('ip', 0), ('flags', '0x202'), ('orig_ax', '0xffffffffffffffff'), ('fs_base', '0x801490'), ('gs_base', '0x0'), ('cs', '0x33'), ('ss', '0x2b'), ('ds', 0), ('es', 0), ('fs', 0), ('gs', 0), ('mode', 'NATIVE')]),)
('WARNING: floating point registers not fully supported',)
('Dumped image file', './x86-64/core-14775.img')
('Core file template created',)
('Loaded image file', './files.img')
('Dumped image file', './x86-64/files.img')
('Files image transformed',)
('Copied ids file',)
('Loaded image file', './core-14775.img')
('Loaded image file', './x86-64/core-14775.img')
('Loaded image file', './pagemap-14775.img')
('Stack Offset: ', 38592)
('Loaded image file', './x86-64/pagemap-14775.img')
('Stack Offset: ', 38592)
Traceback (most recent call last):
  File "/home/ubuntu/TransProc/criu-3.15/crit/crit", line 6, in <module>
    cli.main()
  File "/home/ubuntu/TransProc/criu-3.15/crit/pycriu/cli.py", line 844, in main
    opts["func"](opts)
  File "/home/ubuntu/TransProc/criu-3.15/crit/pycriu/cli.py", line 551, in recode
    converter.recode()
  File "/home/ubuntu/TransProc/criu-3.15/crit/pycriu/converter.py", line 702, in recode
    self.transform_stack_and_regs()
  File "/home/ubuntu/TransProc/criu-3.15/crit/pycriu/converter.py", line 665, in transform_stack_and_regs
    self.dest_rewrite_ctx.regset = self.dest_rewrite_ctx.activations[0].regset
IndexError: list index out of range
```

(The conversion x86-64->aarch64 worked well).

Is there something that I'm doing wrong or is this not fully supported? I've seen the [issue](https://github.com/ssrg-vt/TransProc/wiki/Known-Issues) regarding VMAs.

This would be useful for my work as well, so if it's feasible to fix, I can also take it up.

**Comment by xjtuwxg** [comment]
We seem don't support to start the program from x86-64 (maybe I'm wrong).

**Comment by blackgeorge-boom** [comment]
In the end, I manage to surpass this issue: I think the problem was when the (emulated on QEMU) arm machine was dumping the program, the program was in an inconsistent state, i.e., not in a migration point.

Not sure what caused it (maybe the very slow emulation on QEMU from x86?), but it works now.

**Comment by blackgeorge-boom** [comment]
> We seem don't support to start the program from x86-64 (maybe I'm wrong).

I have opened another issue related to vmas: #19 

But, if you say that restoring on x86 may not be possible, it might be related to this vma issue?
